"""
data_classes.py

This module defines the data models used throughout the application to represent
recommendations generated by the LLM (Large Language Model). It leverages Pydantic's
BaseModel for data validation, serialization, and structured output.

The module includes the following classes:
- Recommendation: Represents a single recommendation item.
- Recommendations: Represents a collection of Recommendation objects.
- RecommendationsResponse: Represents the response format for recommendations
  tied to a specific member.
"""

from pydantic import BaseModel
from typing import List


class Recommendation(BaseModel):
    """
    Represents an individual recommendation from the LLM.

    Attributes:
        title (str): The title or name of the recommended item.
        category (str): The category or type of the recommendation.
        explanation (str): A textual explanation or justification for the recommendation.
    """

    title: str
    category: str
    explanation: str


class Recommendations(BaseModel):
    """
    Represents a collection of Recommendation objects.

    Attributes:
        recommendations (List[Recommendation]): A list of Recommendation items.
    """

    recommendations: List[Recommendation]


class RecommendationsResponse(BaseModel):
    """
    Represents the response payload that ties recommendations to a specific member.

    Attributes:
        member_id (str): The unique identifier of the member for whom recommendations are generated.
        recommendations (List[Recommendation]): A list of Recommendation objects for the member.
    """

    member_id: str
    recommendations: List[Recommendation]
